apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: POD A
        image: my-image
        resources:
          limits:
            memory: "400Mi"
        volumeMounts:
        - name: csv-data
          mountPath: /app/data.csv
          subPath: data.csv
      - name: POD B
        image: my-image
        resources:
          limits:
            memory: "200Mi"
        volumeMounts:
        - name: csv-data
          mountPath: /app/data.csv
          subPath: data.csv
      - name: POD C
        image: my-image
        resources:
          limits:
            memory: "400Mi"
        volumeMounts:
        - name: csv-data
          mountPath: /app/data.csv
          subPath: data.csv
      volumes:
      - name: csv-data
        configMap:
          name: my-csv
