apiVersion: v1
kind: Pod
metadata:
  name: mediawiki
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: POD A
        image: mediawiki
        resources:
          limits:
            memory: "400Mi"
      - name: POD B
        image: mediawiki
        resources:
          limits:
            memory: "200Mi"
      - name: POD C
        image: mediawiki
        resources:
          limits:
            memory: "400Mi"
